### ISSUE TITLE
(chore) Decide on Persistence Mechanism

### ISSUE THREAD

**Issue by TristanHoladay** [Apperators/chat_app#3]
## Description
What kind of persistence mechanism do we want to use?

1. Actual database
2. In memory storage

**Comment by TristanHoladay** [comment]
mongodb-memory-server

**Comment by TristanHoladay** [comment]
SQLITE https://www.sqlite.org/inmemorydb.html
PRISMA https://www.prisma.io/docs/getting-started/quickstart

**Comment by jcgentr** [comment]
https://vercel.com/guides/nextjs-prisma-postgres
https://github.com/prisma/blogr-nextjs-prisma/tree/main
https://www.prisma.io/docs/reference/api-reference/command-reference

**Comment by jcgentr** [comment]
remove dummy models when we go to actually develop application
