### ISSUE TITLE
(chore) Design Library

### ISSUE THREAD

**Issue by TristanHoladay** [Apperators/chat_app#4]
## Description
What libraries do we want to use for our design / css?

### Designs
We can use the figma on the chat group challenge for design.           
https://devchallenges.io/challenges/UgCqszKR7Q7oqb4kRfI0

**Comment by TristanHoladay** [comment]
Chakra-UI
Emotion (spike)

**Comment by jcgentr** [comment]
https://chakra-ui.com/guides/first-steps
https://emotion.sh/docs/styled

ChakraUI has been added to the project. Emotion came with the ChakraUI installation process.
